### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by goldcome** [tobru/bupper#2]
today , update it ,but  find it is not working

```
staff@ubuntu:/usr/local/app/bupper$ bupper -h
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- os (LoadError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/bin/bupper:8:in `<main>'
```
Environment：
```
ruby version: 2.4
ubuntu: 16.04
```

**Comment by CristianCantoro** [comment]
I have the same issue, I am using [rvm](http://rvm.io/) and I've tried using previous versions of ruby, from `2.0` to  `2.4` (current stable) and also `1.9` and `1.8`. I have the exact issue with all `2.X` versions of ruby, the `1.X` version give also a different error (but they are now unmaintained).
